const hre = require("hardhat");

async function main() {
    console.log("Starting ZK Guardian Deployment...");

    // 1. Deploy Groth16Verifier (Generated by Circom)
    const Groth16Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
    const verifier = await Groth16Verifier.deploy();
    await verifier.waitForDeployment();
    const verifierAddr = await verifier.getAddress();
    console.log(`✅ Groth16Verifier deployed to: ${verifierAddr}`);

    // 2. Deploy ZKGuardianAudit (The Audit Log)
    const ZKGuardianAudit = await hre.ethers.getContractFactory("ZKGuardianAudit");
    const audit = await ZKGuardianAudit.deploy(verifierAddr);
    await audit.waitForDeployment();
    const auditAddr = await audit.getAddress();
    console.log(`✅ ZKGuardianAudit deployed to: ${auditAddr}`);

    // 3. Deploy ConsentRevocationRegistry
    const ConsentRevocationRegistry = await hre.ethers.getContractFactory("ConsentRevocationRegistry");
    const registry = await ConsentRevocationRegistry.deploy();
    await registry.waitForDeployment();
    const registryAddr = await registry.getAddress();
    console.log(`✅ ConsentRevocationRegistry deployed to: ${registryAddr}`);

    console.log("\n--- Deployment Summary ---");
    console.log(`Verifier:  ${verifierAddr}`);
    console.log(`Audit Log: ${auditAddr}`);
    console.log(`Registry:  ${registryAddr}`);

    // 4. Verify on PolygonScan (if on Amoy)
    if (hre.network.name === "amoy") {
        console.log("\nWaiting for block confirmations...");
        await audit.deploymentTransaction().wait(5); // Wait 5 blocks

        console.log("Verifying ZKGuardianAudit...");
        try {
            await hre.run("verify:verify", {
                address: auditAddr,
                constructorArguments: [verifierAddr],
            });
        } catch (e) {
            console.log("Verification failed (or already verified):", e.message);
        }

        console.log("Verifying ConsentRevocationRegistry...");
        try {
            await hre.run("verify:verify", {
                address: registryAddr,
                constructorArguments: [],
            });
        } catch (e) {
            console.log("Verification failed:", e.message);
        }
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
