#!/bin/bash
#
# ZK Guardian - Generate Development Wallets
# Creates test wallets for local development
#
# Usage: ./scripts/generate-wallets.sh
#
# WARNING: These wallets are for development only!
# Never use these addresses on mainnet with real funds.
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.local"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check for Node.js
check_node() {
    if ! command -v node &> /dev/null; then
        log_error "Node.js is required. Please install Node.js v18+."
        exit 1
    fi
}

# Generate wallets using ethers.js
generate_wallets() {
    log_info "Generating development wallets..."
    
    node << 'EOF'
const { Wallet } = require('ethers');

// Generate wallets
const deployer = Wallet.createRandom();
const operator = Wallet.createRandom();
const patient1 = Wallet.createRandom();
const clinician1 = Wallet.createRandom();

console.log('# ZK Guardian Development Wallets');
console.log('# WARNING: For development only! Never use on mainnet.');
console.log('#');
console.log('# Deployer Wallet (for contract deployment)');
console.log(`DEPLOYER_ADDRESS=${deployer.address}`);
console.log(`DEPLOYER_PRIVATE_KEY=${deployer.privateKey}`);
console.log('#');
console.log('# Operator Wallet (for gateway transactions)');
console.log(`OPERATOR_ADDRESS=${operator.address}`);
console.log(`OPERATOR_PRIVATE_KEY=${operator.privateKey}`);
console.log('#');
console.log('# Test Patient Wallet');
console.log(`TEST_PATIENT_ADDRESS=${patient1.address}`);
console.log(`TEST_PATIENT_PRIVATE_KEY=${patient1.privateKey}`);
console.log('#');
console.log('# Test Clinician Wallet');
console.log(`TEST_CLINICIAN_ADDRESS=${clinician1.address}`);
console.log(`TEST_CLINICIAN_PRIVATE_KEY=${clinician1.privateKey}`);
console.log('#');
console.log('# Mnemonic phrases (for wallet recovery - keep secure!)');
console.log(`# Deployer: ${deployer.mnemonic?.phrase}`);
console.log(`# Operator: ${operator.mnemonic?.phrase}`);
console.log(`# Patient: ${patient1.mnemonic?.phrase}`);
console.log(`# Clinician: ${clinician1.mnemonic?.phrase}`);
EOF
}

# Add to .env.local
append_to_env() {
    if [ -f "$ENV_FILE" ]; then
        log_warn ".env.local already exists. Appending wallet config..."
        echo "" >> "$ENV_FILE"
        echo "# === Generated Wallets $(date) ===" >> "$ENV_FILE"
    else
        log_info "Creating .env.local..."
        echo "# ZK Guardian Local Environment" > "$ENV_FILE"
        echo "# Generated by ./scripts/generate-wallets.sh" >> "$ENV_FILE"
        echo "" >> "$ENV_FILE"
    fi
    
    generate_wallets >> "$ENV_FILE"
    
    log_info "Wallets added to $ENV_FILE"
}

# Print to console only
print_wallets() {
    log_warn "Printing wallets to console (not saving to file)..."
    echo ""
    generate_wallets
    echo ""
}

# Fund wallets on testnet (if using Polygon Amoy)
fund_instructions() {
    log_info "To fund wallets on Polygon Amoy testnet:"
    echo "  1. Visit https://faucet.polygon.technology/"
    echo "  2. Enter each wallet address"
    echo "  3. Request test MATIC"
    echo ""
    echo "  Alternatively, use the Alchemy faucet:"
    echo "  https://www.alchemy.com/faucets/polygon-amoy"
}

# Main
main() {
    check_node
    
    case "${1:-save}" in
        save)
            append_to_env
            ;;
        print)
            print_wallets
            ;;
        *)
            echo "Usage: $0 [save|print]"
            echo "  save  - Generate and save to .env.local (default)"
            echo "  print - Generate and print to console only"
            exit 1
            ;;
    esac
    
    echo ""
    fund_instructions
    
    log_info "Wallet generation complete!"
}

main "$@"
