/**
 * Blockchain Utility Module
 * 
 * Centralized blockchain interaction logic for consistent transaction handling.
 * Provides ethers.js provider setup, contract factories, and transaction utilities.
 * 
 * Per Development Guide §1 and Technical Blueprint §5.
 */

import { ethers, Contract, ContractTransactionResponse, TransactionReceipt } from 'ethers';
import { env } from '../config/env.js';
import { getGatewayPrivateKey } from '../config/secrets.js';
import { logger } from '../lib/logger.js';
import { prometheusMetrics } from '../metrics/prometheus.js';

// Contract ABIs (imported from compiled artifacts)
// Note: Artifacts are generated by 'pnpm contracts compile'
import ZKGuardianAuditABI from '../../../contracts/artifacts/src/ZKGuardianAudit.sol/ZKGuardianAudit.json' with { type: 'json' };
import ConsentRevocationRegistryABI from '../../../contracts/artifacts/src/ConsentRevocationRegistry.sol/ConsentRevocationRegistry.json' with { type: 'json' };
import SecureVerifierABI from '../../../contracts/artifacts/src/AccessIsAllowedSecureVerifier.sol/AccessIsAllowedSecureVerifier.json' with { type: 'json' };

// Types

export interface TransactionResult {
    success: boolean;
    txHash?: string;
    blockNumber?: number;
    gasUsed?: bigint;
    error?: string;
}

export interface GasEstimate {
    gasLimit: bigint;
    maxFeePerGas: bigint;
    maxPriorityFeePerGas: bigint;
    estimatedCost: string; // In POL/MATIC
}

export interface ContractAddresses {
    verifier: string;
    audit: string;
    registry: string;
}

// Provider & Wallet Management

let providerInstance: ethers.JsonRpcProvider | null = null;
let walletInstance: ethers.Wallet | null = null;

/**
 * Get the Polygon Amoy provider (singleton)
 */
export function getProvider(): ethers.JsonRpcProvider {
    if (!providerInstance) {
        if (!env.POLYGON_AMOY_RPC) {
            throw new Error('POLYGON_AMOY_RPC not configured');
        }
        providerInstance = new ethers.JsonRpcProvider(env.POLYGON_AMOY_RPC);
        logger.info({ rpc: env.POLYGON_AMOY_RPC }, 'Blockchain provider initialized');
    }
    return providerInstance;
}

/**
 * Get the gateway wallet for signing transactions
 */
export async function getWallet(): Promise<ethers.Wallet> {
    if (!walletInstance) {
        const privateKey = await getGatewayPrivateKey();
        const provider = getProvider();
        walletInstance = new ethers.Wallet(privateKey, provider);
        logger.info({ address: walletInstance.address }, 'Gateway wallet initialized');
    }
    return walletInstance;
}

/**
 * Get wallet address without exposing private key
 */
export async function getWalletAddress(): Promise<string> {
    const wallet = await getWallet();
    return wallet.address;
}

/**
 * Check wallet balance
 */
export async function getWalletBalance(): Promise<{ balance: string; isLow: boolean }> {
    const wallet = await getWallet();
    const provider = getProvider();
    const balance = await provider.getBalance(wallet.address);
    const balanceInMatic = ethers.formatEther(balance);
    const isLow = parseFloat(balanceInMatic) < 0.1;

    if (isLow) {
        logger.warn({ address: wallet.address, balance: balanceInMatic }, 'Wallet balance low');
    }

    return { balance: balanceInMatic, isLow };
}

// Contract Instances

/**
 * Get the contract addresses from environment
 */
export function getContractAddresses(): ContractAddresses {
    return {
        verifier: env.AUDIT_CONTRACT_ADDRESS?.replace('_VERIFIER', '') || '',
        audit: env.AUDIT_CONTRACT_ADDRESS || '',
        registry: env.CONSENT_REVOCATION_REGISTRY_ADDRESS || ''
    };
}

/**
 * Get ZKGuardianAudit contract instance
 */
export async function getAuditContract(): Promise<Contract> {
    const wallet = await getWallet();
    const addresses = getContractAddresses();

    if (!addresses.audit) {
        throw new Error('AUDIT_CONTRACT_ADDRESS not configured');
    }

    return new Contract(addresses.audit, ZKGuardianAuditABI.abi, wallet);
}

/**
 * Get ConsentRevocationRegistry contract instance
 */
export async function getRevocationContract(): Promise<Contract> {
    const wallet = await getWallet();
    const addresses = getContractAddresses();

    if (!addresses.registry) {
        throw new Error('CONSENT_REVOCATION_REGISTRY_ADDRESS not configured');
    }

    return new Contract(addresses.registry, ConsentRevocationRegistryABI.abi, wallet);
}

/**
 * Get Groth16Verifier contract instance (read-only)
 */
export async function getVerifierContract(): Promise<Contract> {
    const provider = getProvider();
    const addresses = getContractAddresses();

    if (!addresses.verifier) {
        throw new Error('Verifier address not configured');
    }

    return new Contract(addresses.verifier, SecureVerifierABI.abi, provider);
}

// Transaction Utilities

/**
 * Estimate gas for a transaction
 */
export async function estimateGas(
    contract: Contract,
    method: string,
    args: any[]
): Promise<GasEstimate> {
    const provider = getProvider();

    try {
        const gasLimit = await contract[method].estimateGas(...args);
        const feeData = await provider.getFeeData();

        const maxFeePerGas = feeData.maxFeePerGas || ethers.parseUnits('50', 'gwei');
        const maxPriorityFeePerGas = feeData.maxPriorityFeePerGas || ethers.parseUnits('2', 'gwei');

        const estimatedCost = ethers.formatEther(gasLimit * maxFeePerGas);

        return {
            gasLimit,
            maxFeePerGas,
            maxPriorityFeePerGas,
            estimatedCost
        };
    } catch (error: any) {
        logger.error({ error, method }, 'Gas estimation failed');
        throw error;
    }
}

/**
 * Send a transaction with automatic retry and gas management
 */
export async function sendTransaction(
    contract: Contract,
    method: string,
    args: any[],
    options: {
        maxRetries?: number;
        confirmations?: number;
        gasMultiplier?: number;
    } = {}
): Promise<TransactionResult> {
    const {
        maxRetries = 3,
        confirmations = 1,
        gasMultiplier = 1.2
    } = options;

    const startTime = Date.now();
    let lastError: Error | null = null;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            // Estimate gas
            const gasEstimate = await estimateGas(contract, method, args);
            const gasLimit = BigInt(Math.ceil(Number(gasEstimate.gasLimit) * gasMultiplier));

            logger.info({
                method,
                attempt,
                gasLimit: gasLimit.toString(),
                estimatedCost: gasEstimate.estimatedCost
            }, 'Sending transaction');

            // Send transaction
            const tx: ContractTransactionResponse = await contract[method](...args, {
                gasLimit,
                maxFeePerGas: gasEstimate.maxFeePerGas,
                maxPriorityFeePerGas: gasEstimate.maxPriorityFeePerGas
            });

            // Wait for confirmation
            const receipt: TransactionReceipt | null = await tx.wait(confirmations);

            if (!receipt) {
                throw new Error('Transaction receipt is null');
            }

            const duration = Date.now() - startTime;

            // Record metrics
            prometheusMetrics.blockchainTransactions.inc({
                method,
                status: 'success'
            });
            prometheusMetrics.blockchainLatency.observe({ method }, duration / 1000);

            logger.info({
                txHash: receipt.hash,
                blockNumber: receipt.blockNumber,
                gasUsed: receipt.gasUsed.toString(),
                duration
            }, 'Transaction confirmed');

            return {
                success: true,
                txHash: receipt.hash,
                blockNumber: receipt.blockNumber,
                gasUsed: receipt.gasUsed
            };

        } catch (error: any) {
            lastError = error;

            // Check if retryable
            const isRetryable = isRetryableError(error);

            logger.warn({
                method,
                attempt,
                error: error.message,
                isRetryable
            }, 'Transaction attempt failed');

            if (!isRetryable || attempt === maxRetries) {
                break;
            }

            // Exponential backoff
            await sleep(Math.pow(2, attempt) * 1000);
        }
    }

    // All retries failed
    prometheusMetrics.blockchainTransactions.inc({
        method,
        status: 'failed'
    });

    return {
        success: false,
        error: lastError?.message || 'Transaction failed'
    };
}

/**
 * Check if an error is retryable
 */
function isRetryableError(error: any): boolean {
    const retryableMessages = [
        'nonce too low',
        'replacement fee too low',
        'transaction underpriced',
        'network congestion',
        'timeout',
        'ETIMEDOUT',
        'ECONNRESET'
    ];

    const message = error?.message?.toLowerCase() || '';
    return retryableMessages.some(m => message.includes(m.toLowerCase()));
}

/**
 * Sleep utility
 */
function sleep(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

// Event Listening

/**
 * Listen for AccessAudited events
 */
export async function onAccessAudited(
    callback: (event: {
        proofHash: string;
        accessHash: string;
        policyMatch: string;
        timestamp: bigint;
        txHash: string;
    }) => void
): Promise<() => void> {
    const contract = await getAuditContract();

    const listener = (
        proofHash: string,
        accessHash: string,
        policyMatch: string,
        timestamp: bigint,
        event: any
    ) => {
        callback({
            proofHash,
            accessHash,
            policyMatch,
            timestamp,
            txHash: event.log.transactionHash
        });
    };

    contract.on('AccessAudited', listener);

    logger.info('Subscribed to AccessAudited events');

    // Return unsubscribe function
    return () => {
        contract.off('AccessAudited', listener);
        logger.info('Unsubscribed from AccessAudited events');
    };
}

/**
 * Listen for ConsentRevoked events
 */
export async function onConsentRevoked(
    callback: (event: {
        consentHash: string;
        revoker: string;
        reason: string;
        timestamp: bigint;
        txHash: string;
    }) => void
): Promise<() => void> {
    const contract = await getRevocationContract();

    const listener = (
        consentHash: string,
        revoker: string,
        reason: string,
        timestamp: bigint,
        event: any
    ) => {
        callback({
            consentHash,
            revoker,
            reason,
            timestamp,
            txHash: event.log.transactionHash
        });
    };

    contract.on('ConsentRevoked', listener);

    logger.info('Subscribed to ConsentRevoked events');

    return () => {
        contract.off('ConsentRevoked', listener);
        logger.info('Unsubscribed from ConsentRevoked events');
    };
}

// Consent Revocation Helpers

/**
 * Check if a consent has been revoked
 */
export async function isConsentRevoked(consentHash: string): Promise<boolean> {
    const contract = await getRevocationContract();
    return contract.isRevoked(consentHash);
}

/**
 * Check multiple consents at once
 */
export async function checkConsentsRevoked(consentHashes: string[]): Promise<boolean[]> {
    const contract = await getRevocationContract();
    return contract.checkConsents(consentHashes);
}

/**
 * Revoke a consent on-chain
 */
export async function revokeConsent(
    consentHash: string,
    reason: string
): Promise<TransactionResult> {
    const contract = await getRevocationContract();
    return sendTransaction(contract, 'revokeConsent', [consentHash, reason]);
}

// Health Check

/**
 * Check blockchain connectivity
 */
export async function checkBlockchainHealth(): Promise<{
    connected: boolean;
    blockNumber?: number;
    chainId?: string;
    walletBalance?: string;
    error?: string;
}> {
    try {
        const provider = getProvider();
        const [blockNumber, network] = await Promise.all([
            provider.getBlockNumber(),
            provider.getNetwork()
        ]);

        const { balance } = await getWalletBalance();

        return {
            connected: true,
            blockNumber,
            chainId: network.chainId.toString(),
            walletBalance: balance
        };
    } catch (error: any) {
        return {
            connected: false,
            error: error.message
        };
    }
}
